[package]
name = "rvvm-macro"
version = "0.1.0"
edition = "2021"

authors = ["Nero (kvxmmu)"]
description = "macros for the rvvm crate"
license-file = "../../LICENSE"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.14.2"
proc-macro-error = "1.0.4"
quote = "1.0.23"
syn = "1.0.107"
