[package]
name = "rvvm"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["packages/*"]

[dependencies]
rvvm-sys = { path = "packages/rvvm-sys" }
