[package]
name = "rvvm"
version = "0.2.1"
edition = "2021"

readme = "README.md"
license-file = "LICENSE"

[workspace]
members = ["packages/*"]

[dependencies]
integral-enum = "1.2.1"
thiserror = "1.0.38"

rvvm-sys = { version = "0.1.0", path = "packages/rvvm-sys" }
