[package]
name = "rvvm-sys"
version = "1.0.1"
edition = "2021"

authors = ["Nero (kvxmmu)"]
readme = "README.md"
description = "Raw ffi bindings to the RVVM's public API"
license-file = "../../LICENSE"

repository = "https://github.com/RVVM-rs/rvvm"
links = "rvvm"

[features]
default = []
dynamic = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.63.0"
